// <auto-generated />
using System;
using Matplan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Matplan.Infrastructure.Migrations
{
    [DbContext(typeof(MatplanDBContext))]
    partial class MatplanDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Matplan.EntityModels.Models.Artikel_ART", b =>
                {
                    b.Property<long>("ART_ArtikelNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ART_ArtikelNr"));

                    b.Property<long?>("ART_ART_ArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ART_AgentDatum")
                        .HasColumnType("datetime");

                    b.Property<int?>("ART_AktDagar")
                        .HasColumnType("int");

                    b.Property<byte?>("ART_Aktuell")
                        .HasColumnType("tinyint");

                    b.Property<string>("ART_AltBild")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("ART_AnsvUser")
                        .HasColumnType("bigint");

                    b.Property<int?>("ART_AntBOM")
                        .HasColumnType("int");

                    b.Property<int?>("ART_AntDAP")
                        .HasColumnType("int");

                    b.Property<int?>("ART_AntalBlogposter")
                        .HasColumnType("int");

                    b.Property<string>("ART_ArtikelNamn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ART_BastForeDatum")
                        .HasColumnType("datetime");

                    b.Property<int?>("ART_BehovTot")
                        .HasColumnType("int");

                    b.Property<int?>("ART_Belopp")
                        .HasColumnType("int");

                    b.Property<int?>("ART_BeloppFinns")
                        .HasColumnType("int");

                    b.Property<int?>("ART_DAP_Kvantitet")
                        .HasColumnType("int");

                    b.Property<int?>("ART_DaglForbr")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ART_DateMod")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ART_DateNy")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ART_DateUppdat")
                        .HasColumnType("datetime");

                    b.Property<string>("ART_Enhet")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<byte?>("ART_Fettsnalt")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ART_FinnsAlltidHemma")
                        .HasColumnType("int");

                    b.Property<string>("ART_FlashAdd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ART_Forslag")
                        .HasColumnType("int");

                    b.Property<int?>("ART_ForslagIdag")
                        .HasColumnType("int");

                    b.Property<byte?>("ART_GI")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ART_GL")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ART_Glutenfritt")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ART_GramPerDl")
                        .HasColumnType("int");

                    b.Property<int?>("ART_GramPerSt")
                        .HasColumnType("int");

                    b.Property<int?>("ART_GramPerTsk")
                        .HasColumnType("int");

                    b.Property<string>("ART_Grupp")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ART_HI")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("ART_Husman")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("ART_Image")
                        .HasColumnType("image");

                    b.Property<string>("ART_ImgTyp")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<int?>("ART_IngariAnt")
                        .HasColumnType("int");

                    b.Property<int?>("ART_Inkop")
                        .HasColumnType("int");

                    b.Property<string>("ART_InkopEnhet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("ART_JustVeckodag")
                        .HasColumnType("tinyint");

                    b.Property<string>("ART_Kat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("ART_Klassisk")
                        .HasColumnType("tinyint");

                    b.Property<string>("ART_KlientNamn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("ART_LCHF")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ART_LagerBelopp")
                        .HasColumnType("int");

                    b.Property<int?>("ART_LagerSaldo")
                        .HasColumnType("int");

                    b.Property<string>("ART_LagerSaldoSt")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ART_LagersaldoUt")
                        .HasColumnType("int");

                    b.Property<string>("ART_Lagring")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<byte?>("ART_Laktosfritt")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ART_Ledtid")
                        .HasColumnType("int");

                    b.Property<int?>("ART_Losvikt")
                        .HasColumnType("int");

                    b.Property<string>("ART_Memo")
                        .HasColumnType("text");

                    b.Property<int?>("ART_MinLager")
                        .HasColumnType("int");

                    b.Property<byte?>("ART_OpOrdNrLast")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ART_Pris")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ART_PrisDatum")
                        .HasColumnType("datetime");

                    b.Property<int?>("ART_PrisFrp")
                        .HasColumnType("int");

                    b.Property<string>("ART_ProduktArtikelNamn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("ART_ProduktArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<int?>("ART_Publicera")
                        .HasColumnType("int");

                    b.Property<int?>("ART_Rang")
                        .HasColumnType("int");

                    b.Property<int?>("ART_RankProcFinns")
                        .HasColumnType("int");

                    b.Property<int?>("ART_Sats")
                        .HasColumnType("int");

                    b.Property<string>("ART_Sok")
                        .HasMaxLength(2500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2500)");

                    b.Property<string>("ART_Sok_Ravaror")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<byte?>("ART_TillPlan")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ART_Typ")
                        .HasColumnType("int");

                    b.Property<string>("ART_URL")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ART_URL_Link")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ART_URL_Text")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ART_USK_KvantitetForslag")
                        .HasColumnType("int");

                    b.Property<long>("ART_USR_Rsn")
                        .HasColumnType("bigint");

                    b.Property<string>("ART_Upload")
                        .HasColumnType("text");

                    b.Property<string>("ART_UserMod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ART_UserNy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ART_VG")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("ART_Vego")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ART_VideoJa")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ART_kCal")
                        .HasColumnType("int");

                    b.Property<int?>("ART_kCalFormula")
                        .HasColumnType("int");

                    b.Property<int?>("ART_kCalSum")
                        .HasColumnType("int");

                    b.HasKey("ART_ArtikelNr")
                        .HasName("Artikel_ART_PK");

                    b.HasIndex(new[] { "ART_ART_ArtikelNr" }, "Artikel_ART_AK1");

                    b.HasIndex(new[] { "ART_USR_Rsn" }, "Artikel_ART_AK2");

                    b.ToTable("Artikel_ART");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Batch_BAT", b =>
                {
                    b.Property<long>("BAT_Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("BAT_AntalLoopar")
                        .HasColumnType("bigint");

                    b.Property<bool?>("BAT_BASE64")
                        .HasColumnType("bit");

                    b.Property<bool?>("BAT_CHMOD")
                        .HasColumnType("bit");

                    b.Property<bool?>("BAT_COMPRESS")
                        .HasColumnType("bit");

                    b.Property<byte?>("BAT_DIBS")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("BAT_IPInfo")
                        .HasColumnType("tinyint");

                    b.Property<short?>("BAT_MAXHEIGHT")
                        .HasColumnType("smallint");

                    b.Property<short?>("BAT_MAXWIDTH")
                        .HasColumnType("smallint");

                    b.Property<string>("BAT_Namn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("BAT_PayPal")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("BAT_QUALITY")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<bool?>("BAT_RESIZE")
                        .HasColumnType("bit");

                    b.Property<string>("BAT_SERVERPATH")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("BAT_SimDatum")
                        .HasColumnType("datetime");

                    b.Property<int?>("BAT_Sleeptime")
                        .HasColumnType("int");

                    b.Property<string>("BAT_URL")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("BAT_Id")
                        .HasName("Batch_BAT_PK");

                    b.ToTable("Batch_BAT");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Behov_BOM_BBM", b =>
                {
                    b.Property<long>("BBM_User")
                        .HasColumnType("bigint");

                    b.Property<long>("BBM_ArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BBM_Datum")
                        .HasColumnType("datetime");

                    b.Property<byte>("BBM_BOM_OpNr")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BBM_BOM_OpOrdNr")
                        .HasColumnType("tinyint");

                    b.Property<int?>("BBM_ART_FinnsAlltidHemma")
                        .HasColumnType("int");

                    b.Property<int?>("BBM_BOMUt")
                        .HasColumnType("int");

                    b.Property<int?>("BBM_BOMUtSEK")
                        .HasColumnType("int");

                    b.Property<int?>("BBM_BehovRepl")
                        .HasColumnType("int");

                    b.Property<int?>("BBM_Faktor")
                        .HasColumnType("int");

                    b.Property<long?>("BBM_IngArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("BBM_IngDatum")
                        .HasColumnType("datetime");

                    b.Property<long?>("BBM_IngUser")
                        .HasColumnType("bigint");

                    b.Property<byte?>("BBM_JustVeckodag")
                        .HasColumnType("tinyint");

                    b.Property<int?>("BBM_Kvant")
                        .HasColumnType("int");

                    b.Property<int?>("BBM_Ledtid")
                        .HasColumnType("int");

                    b.Property<byte?>("BBM_RecEnh")
                        .HasColumnType("tinyint");

                    b.Property<int?>("BBM_RecKvant")
                        .HasColumnType("int");

                    b.Property<int?>("BBM_Sats")
                        .HasColumnType("int");

                    b.HasKey("BBM_User", "BBM_ArtikelNr", "BBM_Datum", "BBM_BOM_OpNr", "BBM_BOM_OpOrdNr")
                        .HasName("Behov_BOM_BBM_PK");

                    b.HasIndex(new[] { "BBM_ArtikelNr" }, "AK_ArtikelNr");

                    b.HasIndex(new[] { "BBM_IngUser", "BBM_IngDatum", "BBM_IngArtikelNr" }, "AK_BBM2");

                    b.HasIndex(new[] { "BBM_IngArtikelNr" }, "AK_IngArtikelNr");

                    b.ToTable("Behov_BOM_BBM");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Bill_Of_Material_BOM", b =>
                {
                    b.Property<long>("BOM_ArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<byte>("BOM_OpNr")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BOM_OpOrdNr")
                        .HasColumnType("tinyint");

                    b.Property<long?>("BOM_ART_IngArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<string>("BOM_Anm")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("BOM_ArtTyp")
                        .HasColumnType("int");

                    b.Property<int?>("BOM_Belopp")
                        .HasColumnType("int");

                    b.Property<int?>("BOM_BeloppFinns")
                        .HasColumnType("int");

                    b.Property<int?>("BOM_BeloppIngFinns")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BOM_DateTimeStamp")
                        .HasColumnType("datetime");

                    b.Property<int?>("BOM_IngArtTyp")
                        .HasColumnType("int");

                    b.Property<long?>("BOM_IngArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<string>("BOM_IngEnhet")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<int?>("BOM_IngPris")
                        .HasColumnType("int");

                    b.Property<int?>("BOM_IngSats")
                        .HasColumnType("int");

                    b.Property<int?>("BOM_IngkCal")
                        .HasColumnType("int");

                    b.Property<byte?>("BOM_JustVeckodag")
                        .HasColumnType("tinyint");

                    b.Property<int?>("BOM_Kvant")
                        .HasColumnType("int");

                    b.Property<byte?>("BOM_Maltid")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("BOM_Matratt")
                        .HasColumnType("tinyint");

                    b.Property<string>("BOM_Memo")
                        .HasColumnType("text");

                    b.Property<byte?>("BOM_RecEnh")
                        .HasColumnType("tinyint");

                    b.Property<int?>("BOM_RecKvant")
                        .HasColumnType("int");

                    b.Property<int?>("BOM_Sats")
                        .HasColumnType("int");

                    b.Property<int?>("BOM_USK_KvantitetForslag")
                        .HasColumnType("int");

                    b.Property<long?>("BOM_USR_Rsn")
                        .HasColumnType("bigint");

                    b.Property<int?>("BOM_kCal")
                        .HasColumnType("int");

                    b.HasKey("BOM_ArtikelNr", "BOM_OpNr", "BOM_OpOrdNr")
                        .HasName("Bill_Of_Material_BOM_PK");

                    b.HasIndex(new[] { "BOM_IngArtikelNr" }, "AK1");

                    b.HasIndex(new[] { "BOM_ArtikelNr" }, "AK2");

                    b.ToTable("Bill_Of_Material_BOM");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Blog_BLG", b =>
                {
                    b.Property<long>("BLG_Rsn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BLG_Rsn"));

                    b.Property<string>("BLG_Amne")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("BLG_Datum")
                        .HasColumnType("datetime");

                    b.Property<string>("BLG_DatumUser")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("BLG_Gilla")
                        .HasColumnType("int");

                    b.Property<long?>("BLG_OrgArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<string>("BLG_RelAmne")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("BLG_RelRsn")
                        .HasColumnType("bigint");

                    b.Property<string>("BLG_Signatur")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BLG_Text")
                        .HasColumnType("text");

                    b.Property<long?>("BLG_USR_Rsn")
                        .HasColumnType("bigint");

                    b.HasKey("BLG_Rsn")
                        .HasName("Blog_BLG_PK");

                    b.HasIndex(new[] { "BLG_Amne", "BLG_Datum" }, "AK_AmneDatum");

                    b.HasIndex(new[] { "BLG_DatumUser" }, "AK_DAtumUser");

                    b.HasIndex(new[] { "BLG_OrgArtikelNr", "BLG_Rsn" }, "AK_OrgArtnr");

                    b.HasIndex(new[] { "BLG_Rsn", "BLG_RelRsn" }, "AK_Rsn_RelRsn");

                    b.ToTable("Blog_BLG");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.DUMMY", b =>
                {
                    b.Property<string>("DU_K1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DU_BEN")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DU_K1")
                        .HasName("DUMMY_PK");

                    b.ToTable("DUMMY");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.DagPlan_DAP", b =>
                {
                    b.Property<long>("DAP_Rsn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DAP_Rsn"));

                    b.Property<long?>("DAP_ART_ArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<int?>("DAP_ART_kCalFormula")
                        .HasColumnType("int");

                    b.Property<string>("DAP_AltBild")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DAP_Anm")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("DAP_ArtTyp")
                        .HasColumnType("int");

                    b.Property<string>("DAP_ArtikelNamn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("DAP_ArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<string>("DAP_Dag")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DAP_Datum")
                        .HasColumnType("datetime");

                    b.Property<string>("DAP_Enhet")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("DAP_FrTi")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("DAP_ImgTyp")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<int?>("DAP_InkopBered")
                        .HasColumnType("int");

                    b.Property<long?>("DAP_KLS_ArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<long?>("DAP_KLS_User")
                        .HasColumnType("bigint");

                    b.Property<int?>("DAP_Kvantitet")
                        .HasColumnType("int");

                    b.Property<int?>("DAP_LagerSaldo")
                        .HasColumnType("int");

                    b.Property<byte?>("DAP_Maltid")
                        .HasColumnType("tinyint");

                    b.Property<string>("DAP_Manad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("DAP_Matratt")
                        .HasColumnType("tinyint");

                    b.Property<int?>("DAP_SLD_Pris")
                        .HasColumnType("int");

                    b.Property<int?>("DAP_SLD_Summa")
                        .HasColumnType("int");

                    b.Property<int?>("DAP_Sats")
                        .HasColumnType("int");

                    b.Property<string>("DAP_UddaVecka")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<long?>("DAP_User")
                        .HasColumnType("bigint");

                    b.Property<int?>("DAP_Vecka")
                        .HasColumnType("int");

                    b.HasKey("DAP_Rsn")
                        .HasName("DagPlan_DAP_PK");

                    b.HasIndex(new[] { "DAP_ART_ArtikelNr" }, "AK_ART_ArtikelNr");

                    b.HasIndex(new[] { "DAP_ArtikelNr" }, "AK_ArtikelNr");

                    b.HasIndex(new[] { "DAP_User" }, "AK_USR");

                    b.ToTable("DagPlan_DAP");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.EmiR_MAIL_SMT", b =>
                {
                    b.Property<long>("SMT_RSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SMT_RSN"));

                    b.Property<string>("SMT_AttachFiles")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("SMT_DateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("SMT_MsgText")
                        .HasColumnType("text");

                    b.Property<string>("SMT_RecipientsCC")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SMT_RecipientsTo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SMT_Status")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("SMT_Subject")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SMT_User")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SMT_RSN")
                        .HasName("EmiR_MAIL_SMT_PK");

                    b.ToTable("EmiR_MAIL_SMT");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.KalendarisktLagerSaldo_KLS", b =>
                {
                    b.Property<long>("KLS_User")
                        .HasColumnType("bigint");

                    b.Property<long>("KLS_ArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("KLS_Datum")
                        .HasColumnType("datetime");

                    b.Property<long?>("KLS_ART_ART_ArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<long?>("KLS_ART_AnsvUser")
                        .HasColumnType("bigint");

                    b.Property<int?>("KLS_ART_Faktor")
                        .HasColumnType("int");

                    b.Property<int>("KLS_ART_Inkop")
                        .HasColumnType("int");

                    b.Property<string>("KLS_ART_InkopEnhet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("KLS_ART_Ledtid")
                        .HasColumnType("bigint");

                    b.Property<int?>("KLS_ART_Losvikt")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_ART_Pris")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KLS_ART_PrisDatum")
                        .HasColumnType("datetime");

                    b.Property<int?>("KLS_ART_PrisFrp")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_ART_Sats")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_ART_kCalFormula")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_AntBBM")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_ArtTyp")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_BOMUt")
                        .HasColumnType("int");

                    b.Property<string>("KLS_BOMUtInkopEnhet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("KLS_Behov")
                        .HasColumnType("int");

                    b.Property<string>("KLS_BehovInkopEnhet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("KLS_BehovRepl")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_BehovSEK")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_BehovTot")
                        .HasColumnType("int");

                    b.Property<string>("KLS_BehovTotInkopEnhet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("KLS_BestDatum")
                        .HasColumnType("datetime");

                    b.Property<int?>("KLS_DAPIn")
                        .HasColumnType("int");

                    b.Property<string>("KLS_Dag")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("KLS_DaglForbr")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KLS_DateStamp")
                        .HasColumnType("datetime");

                    b.Property<string>("KLS_Enhet")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<int?>("KLS_Extra")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_ExtraSt")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_Forslag")
                        .HasColumnType("int");

                    b.Property<string>("KLS_ForslagInkopEnhet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KLS_ForslagInkopSEK")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("KLS_ForslagSEK")
                        .HasColumnType("int");

                    b.Property<byte?>("KLS_Forslag_OK")
                        .HasColumnType("tinyint");

                    b.Property<int?>("KLS_GramPerDl")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_GramPerSt")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_IngSaldo")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_KalSaldo")
                        .HasColumnType("int");

                    b.Property<string>("KLS_KalSaldoStr")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("KLS_KalSaldoUt")
                        .HasColumnType("int");

                    b.Property<string>("KLS_KalSaldoUtInkopEnhet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KLS_KlientNamn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("KLS_LagerSaldo")
                        .HasColumnType("int");

                    b.Property<string>("KLS_Manad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("KLS_MinLager")
                        .HasColumnType("int");

                    b.Property<string>("KLS_ProduktArtikelNamn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("KLS_PubliceraRelKonstant")
                        .HasColumnType("bit");

                    b.Property<long?>("KLS_RelArtikelNr")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("KLS_RelDatum")
                        .HasColumnType("datetime");

                    b.Property<long?>("KLS_RelUser")
                        .HasColumnType("bigint");

                    b.Property<string>("KLS_Rest_FattasKvar")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("KLS_SLD_DaglForbr")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_SLD_Forslag")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_SaldoSt")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_SatsLosvikt")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_SistaKLS")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_TillvFobrukatNu")
                        .HasColumnType("int");

                    b.Property<int?>("KLS_TillvLagerNu")
                        .HasColumnType("int");

                    b.Property<string>("KLS_UddaVecka")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("KLS_VG")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("KLS_Vecka")
                        .HasColumnType("int");

                    b.HasKey("KLS_User", "KLS_ArtikelNr", "KLS_Datum")
                        .HasName("KalendarisktLagerSaldo_KLS_PK");

                    b.HasIndex(new[] { "KLS_ART_ART_ArtikelNr" }, "AK_ART_ART_ArtikelNr");

                    b.HasIndex(new[] { "KLS_ArtikelNr" }, "AK_ArtikelNr");

                    b.HasIndex(new[] { "KLS_RelUser", "KLS_RelArtikelNr", "KLS_RelDatum" }, "AK_Rel_KLS");

                    b.HasIndex(new[] { "KLS_User", "KLS_Datum" }, "AK_USR");

                    b.ToTable("KalendarisktLagerSaldo_KLS");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Klient_USK", b =>
                {
                    b.Property<long>("USK_Rsn")
                        .HasColumnType("bigint");

                    b.Property<int?>("USK_AntDAP")
                        .HasColumnType("int");

                    b.Property<int?>("USK_BristSEK")
                        .HasColumnType("int");

                    b.Property<byte?>("USK_Handlar")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("USK_HandlarFr")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("USK_HandlarLo")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("USK_HandlarMa")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("USK_HandlarOn")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("USK_HandlarSo")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("USK_HandlarTi")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("USK_HandlarTo")
                        .HasColumnType("tinyint");

                    b.Property<int?>("USK_KostnadSEK")
                        .HasColumnType("int");

                    b.Property<int?>("USK_KvantitetForslag")
                        .HasColumnType("int");

                    b.Property<int?>("USK_LagerSEK")
                        .HasColumnType("int");

                    b.Property<string>("USK_LicensBetaldStatus")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("USK_LicensBetaldToM")
                        .HasColumnType("datetime");

                    b.Property<string>("USK_Namn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("USK_Rsn")
                        .HasName("Klient_USK_PK");

                    b.HasIndex(new[] { "USK_Namn" }, "UQ__Klient_U__80C58B6474E2CC72")
                        .IsUnique()
                        .HasFilter("[USK_Namn] IS NOT NULL");

                    b.ToTable("Klient_USK");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.SkapaKonto_SKO", b =>
                {
                    b.Property<long>("SKO_RSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SKO_RSN"));

                    b.Property<string>("SKO_EMAIL")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SKO_MEDDELANDE")
                        .HasColumnType("text");

                    b.Property<string>("SKO_NAMN")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SKO_PWD1")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SKO_PWD2")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SKO_SIGNATUR")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SKO_USERID")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("SKO_RSN")
                        .HasName("SkapaKonto_SKO_PK");

                    b.ToTable("SkapaKonto_SKO");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Transaktion_TRN", b =>
                {
                    b.Property<DateTime>("TRN_DateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("TRN_RemoteAddr")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TRN_RemoteLandkod")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("TRN_RemoteRegion")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TRN_RemoteStad")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TRN_Sok")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TRN_USK_Namn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("TRN_USK_Rsn")
                        .HasColumnType("bigint");

                    b.Property<long?>("TRN_USR_Rsn")
                        .HasColumnType("bigint");

                    b.Property<string>("TRN_USR_Signatur")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TRN_DateTime")
                        .HasName("Transaktion_TRN_PK");

                    b.ToTable("Transaktion_TRN");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_ART_Enhet", b =>
                {
                    b.Property<string>("Storedpfu")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.HasKey("Storedpfu")
                        .HasName("Z_ART_Enhet_PK");

                    b.ToTable("Z_ART_Enhet");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_ART_Grupp", b =>
                {
                    b.Property<string>("Storedpfu")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_ART_Grupp_PK");

                    b.ToTable("Z_ART_Grupp");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_ART_Lagring", b =>
                {
                    b.Property<string>("Storedpfu")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_ART_Lagring_PK");

                    b.ToTable("Z_ART_Lagring");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_ART_RecEnh", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_ART_RecEnh_PK");

                    b.ToTable("Z_ART_RecEnh");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_ART_Typ", b =>
                {
                    b.Property<string>("Storedpfu")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_ART_Typ_PK");

                    b.ToTable("Z_ART_Typ");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_AltBild", b =>
                {
                    b.Property<string>("Storedpfu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_AltBild_PK");

                    b.ToTable("Z_AltBild");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_BeredInkop", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_BeredInkop_PK");

                    b.ToTable("Z_BeredInkop");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_BristViaSMS", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_BristViaSMS_PK");

                    b.ToTable("Z_BristViaSMS");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_Datum", b =>
                {
                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime");

                    b.Property<string>("Dag")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Datum")
                        .HasName("Z_Datum_PK");

                    b.ToTable("Z_Datum");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_HI", b =>
                {
                    b.Property<string>("Storedpfu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_HI_PK");

                    b.ToTable("Z_HI");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_Handlar", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_Handlar_PK");

                    b.ToTable("Z_Handlar");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_Ja", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_Ja_PK");

                    b.ToTable("Z_Ja");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_Kat", b =>
                {
                    b.Property<string>("Storedpfu")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_Kat_PK");

                    b.ToTable("Z_Kat");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_Maltid", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_Maltid_PK");

                    b.ToTable("Z_Maltid");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_Matratt", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_Matratt_PK");

                    b.ToTable("Z_Matratt");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_NejJa", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_NejJa_PK");

                    b.ToTable("Z_NejJa");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_Plandag", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_Plandag_PK");

                    b.ToTable("Z_Plandag");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_Steg", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_Steg_PK");

                    b.ToTable("Z_Steg");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_VG", b =>
                {
                    b.Property<string>("Storedpfu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DisplayedVG")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_VG_PK");

                    b.ToTable("Z_VG");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.Z_Veckodag", b =>
                {
                    b.Property<byte>("Storedpfu")
                        .HasColumnType("tinyint");

                    b.Property<string>("Displayed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Storedpfu")
                        .HasName("Z_Veckodag_PK");

                    b.ToTable("Z_Veckodag");
                });

            modelBuilder.Entity("Matplan.EntityModels.Models.ip2location_db5", b =>
                {
                    b.Property<string>("city_name")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("country_code")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("country_name")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("varchar(65)");

                    b.Property<long?>("ip_from")
                        .HasColumnType("bigint");

                    b.Property<long?>("ip_to")
                        .HasColumnType("bigint");

                    b.Property<double?>("latitude")
                        .HasColumnType("float");

                    b.Property<double?>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("region_name")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasIndex(new[] { "ip_from" }, "idx_ip_from");

                    b.HasIndex(new[] { "ip_from", "ip_to" }, "idx_ip_from_to");

                    b.HasIndex(new[] { "ip_to" }, "idx_ip_to");

                    b.ToTable("ip2location_db5");
                });
#pragma warning restore 612, 618
        }
    }
}
